### ISSUE TITLE
3.26.9 failing the patch

### ISSUE THREAD

**Issue by fruch** [scylladb/python-driver-matrix#86]
```
Traceback (most recent call last):

  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/main.py", line 31, in main
    result = runner.run()

  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/run.py", line 202, in run
    if self._checkout_branch() and self._apply_patch_files() and self._install_python_requirements():

  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/run.py", line 121, in _apply_patch_files
    self._run_command_in_shell(f"git apply --check {file_path}")

  File "/jenkins/workspace/scylla-master/driver-tests/python-driver-matrix-test/python-driver-matrix/run.py", line 111, in _run_command_in_shell
    assert status_code == 0, stderr

AssertionError: (None, b'/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\nerror: patch failed: tests/integration/standard/test_custom_cluster.py:26\nerror: tests/integration/standard/test_custom_cluster.py: patch does not apply\n')
```

**Comment by dimakr** [comment]
Reproduced during 2024.1.13 release testing in the run [enterprise-2024.1/driver-tests/python-driver-matrix-test#29](https://jenkins.scylladb.com/job/enterprise-2024.1/job/driver-tests/job/python-driver-matrix-test/29)

**Comment by dimakr** [comment]
@dkropachev can we attend this issue? Seems like it is blocking us from running python driver scylla part of tests (they were not started for this latest 2024.1 release).

**Comment by juliayakovlev** [comment]
reproduced with `2023.1`
https://argus.scylladb.com/tests/driver-matrix-tests/f01a1731-5746-42bd-b69c-183c9043f041

**Comment by dimakr** [comment]
Reproduced again in 2024.1.15 - [[](url)](https://argus.scylladb.com/tests/driver-matrix-tests/685b314d-5d06-44fd-b000-f361a6389768)

The issue is repeating not only for ver, 3.26.9, but also for versions:
datastax 3.29.2 
scylla 3.28.0
Only ver. datastax 3.28.0 is OK.

**Comment by dkropachev** [comment]
Fixed

**Comment by juliayakovlev** [comment]
@dkropachev 

It is still reproduced: https://argus.scylladb.com/tests/driver-matrix-tests/f3d7a7a9-dde2-463d-9e64-513b65a09c9a

**Comment by vponomaryov** [comment]
> [@dkropachev](https://github.com/dkropachev)
> 
> It is still reproduced: https://argus.scylladb.com/tests/driver-matrix-tests/f3d7a7a9-dde2-463d-9e64-513b65a09c9a

Reopening due to this
